[package]
name = "randrem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
human-panic = "1.1"
notify-rust = "4"
rand = "0.8"
