[tool.poetry]
name = "randrem-tg"
version = "0.1.0"
description = ""
authors = ["Lars Quentin <lars@lquenti.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python-telegram-bot = "^21.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
